/**
 * /llms.txt — the site's machine-readable product surface.
 *
 * Generated by src/app/llms.txt/route.ts at build time from this registry
 * plus the canonical facts in content/commercial.ts and the typed content
 * arrays (intent pages, comparisons, blog). It is navigational: a short
 * factual orientation, then links with useful descriptions to the canonical
 * pages. It is deliberately small, contains no instructions to assistants,
 * and duplicates nothing that the linked pages state better.
 *
 * Follows the llms.txt convention: H1, a blockquote summary, short
 * orientation, H2 sections of `- [title](url): description` links, and an
 * "Optional" section for secondary material. Pages with a Markdown alternate
 * are linked to it (`…/index.md`); everything else links to the HTML page.
 *
 * tests/llms.test.ts checks the structure, that every link resolves to a
 * route in the sitemap, and that no stale commercial claim survives here.
 */

import { blogPosts } from "./blog/posts";
import {
  foundingProgramme,
  identity,
  planHierarchy,
  pricingAvailability,
  product,
} from "./commercial";
import { company } from "./company";
import { comparisons } from "./comparisons";
import { intentPages } from "./intent-pages";
import { hasMarkdownAlternate, markdownAlternatePath } from "./markdown-alternates";
import { RETENTION_PATH, retentionPointer } from "./retention";
import { siteSource } from "./site-content";
import { AEGIS_DEFINITION, aegisBoundaries } from "./what-is-squarecampus";

export type LlmsLink = { path: string; title: string; description: string };
export type LlmsSection = { heading: string; intro?: string; links: LlmsLink[] };

const SITE = "https://squarecampus.com";

/** Absolute URL for a route, preferring the Markdown alternate where one exists. */
export function llmsUrl(path: string): string {
  if (path.includes(".")) return `${SITE}${path}`;
  if (hasMarkdownAlternate(path)) return `${SITE}${markdownAlternatePath(path)}`;
  const withSlash = path === "/" ? "/" : path.endsWith("/") ? path : `${path}/`;
  return `${SITE}${withSlash}`;
}

/** Route-only form of a link (`/pricing/`), for the sitemap cross-check. */
export function llmsRoute(path: string): string {
  const p = path.split("#")[0];
  if (p.includes(".")) return p;
  return p === "/" ? "/" : p.endsWith("/") ? p : `${p}/`;
}

const intentPage = (slug: string) => intentPages.find((page) => page.slug === slug);

function intentLink(slug: string, description: string): LlmsLink {
  const page = intentPage(slug);
  if (!page) throw new Error(`llms.ts: unknown intent page "${slug}"`);
  return { path: `/${slug}`, title: page.keyword, description };
}

export const llmsSections: LlmsSection[] = [
  {
    heading: "Evaluate SquareCampus",
    links: [
      {
        path: "/what-is-squarecampus",
        title: "What is SquareCampus",
        description:
          "The canonical definition, the four layers (record, workflow, governance, intelligence), what School OS, governance, exception ownership and accountability mean here, and the direct answer to whether it is an ERP",
      },
      {
        path: "/pricing",
        title: "Pricing",
        description: `How the licence is structured (${pricingAvailability.model.replace(/\.$/, "").replace(/^One/, "one")}), what is included versus separately scoped, what Enterprise adds beyond ERP modules, identity options by plan, and who it is not the right fit for. ${pricingAvailability.short}`,
      },
      {
        path: "/platform",
        title: "Platform",
        description:
          "How the School OS is structured: four layers, the operating cycles it carries, the shared institutional core and the product surfaces",
      },
      {
        path: "/security",
        title: "Security and identity",
        description:
          "Design posture for encryption, role-based access, auditability and India-first hosting; sign-in options by plan and why authorisation stays inside SquareCampus. Documentation is shared through the security review process",
      },
      {
        path: "/rollout",
        title: "Rollout and deployment paths",
        description:
          "Guided implementation sequenced around the academic calendar, and the two deployment paths: coexistence alongside the current stack, and later consolidation if the institution chooses",
      },
      {
        path: "/why-squarecampus",
        title: "Why SquareCampus",
        description: "The comparison against module-based school ERPs, by operating outcome",
      },
      {
        path: "/compare",
        title: "Compare",
        description: `Head-to-head comparisons against named school ERP products (${comparisons.map((c) => c.competitorShort).join(", ")}), each naming the competitor's genuine strengths and who should choose them`,
      },
      {
        path: "/faq",
        title: "FAQ",
        description:
          "Getting started, features, security and data, pricing and support, in the words buyers ask",
      },
    ],
  },
  {
    heading: "Institutional requirements",
    intro:
      "One page per buyer question. Each opens with a direct definition, then the workflows as they run, India-specific realities, a vendor-neutral evaluation list and a FAQ.",
    links: [
      intentLink(
        "multi-campus-school-management-software",
        "Trust-level policy, campus-level execution, roles scoped by campus, and a table on how multi-campus governance differs from merely supporting several campuses"
      ),
      intentLink(
        "school-erp-software",
        "The school ERP category answered honestly, then reframed as connected workflows on one governed record"
      ),
      {
        path: "/school-management-system",
        title: "School management system",
        description:
          "The category page for buyers using that terminology: modules as workflows, India-first fees and compliance, implementation sequence, pricing model",
      },
      intentLink(
        "fee-management-software-for-schools",
        "Term plans, concessions, transport slabs, GST receipts, reminders and month-end reconciliation on one ledger"
      ),
      intentLink(
        "school-attendance-management-system",
        "Attendance as an early-warning workflow with thresholds, owners and follow-up, not only a register"
      ),
      intentLink(
        "school-admission-management-software",
        "Enquiry to enrolment as a staged workflow with owners, document verification and seat allocation"
      ),
      intentLink(
        "school-exam-management-software",
        "Datesheet to report card as a chain of handovers, with marks entry, moderation and re-evaluation on an audit trail"
      ),
      intentLink(
        "parent-communication-app-for-schools",
        "Addressed communication with acknowledgement, replies routed to a named owner, in ten Indian languages"
      ),
      intentLink(
        "school-management-software-for-cbse-schools",
        "CBSE-specific operations: assessment structure, board records and compliance as configuration"
      ),
      intentLink(
        "school-management-software-for-icse-schools",
        "ICSE-specific operations as configuration rather than customisation"
      ),
      intentLink(
        "school-management-software-for-state-board-schools",
        "State-board operations: regional languages, state levies and board formats"
      ),
      {
        path: "/launch-partners/higher-education",
        title: "Higher education",
        description:
          "For private universities and multi-school groups: a governed operating layer that runs alongside the existing ERP, LMS, payment and identity systems. Not a university ERP, SIS or LMS",
      },
      {
        path: "/services",
        title: "Data and integration services",
        description:
          "API and WebSocket integrations with existing tools, ETL pipelines, private deployments",
      },
    ],
  },
  {
    heading: "Intelligence",
    links: [
      {
        path: "/aegis",
        title: "AEGIS",
        description: `${AEGIS_DEFINITION} Boundaries: ${aegisBoundaries.map((b) => b.split(" — ")[0].toLowerCase()).join(", ")}`,
      },
    ],
  },
  {
    heading: "Commercial programmes",
    links: [
      {
        path: "/launch-partners",
        title: "Founding Institutional Partner programme",
        description: `${foundingProgramme.positionsStatement} ${foundingProgramme.nature} Entitlements under the executed agreement: ${foundingProgramme.entitlements.map((e) => e.title.toLowerCase()).join(", ")}`,
      },
    ],
  },
  {
    heading: "Company and trust",
    links: [
      {
        path: "/about",
        title: "About",
        description: `${company.legalNameDisplay}, ${product.operator.locality}. CIN ${company.cin}, incorporated ${company.incorporationDateDisplay}; GSTIN ${company.gstin}. Founder-led`,
      },
      {
        path: "/contact",
        title: "Contact",
        description: "Registered office, corporate identity and contact channels",
      },
      {
        path: "/infrastructure",
        title: "Infrastructure",
        description:
          "Microsoft Azure in India, encryption in transit and at rest, India data-residency posture, Enterprise private deployment on AWS; documentation through security review",
      },
      {
        path: "/privacy-policy",
        title: "Privacy policy",
        description: "How personal data is collected, used, retained and protected",
      },
      {
        path: "/terms-of-service",
        title: "Terms of service",
        description:
          "Subscription terms, acceptable use and the order form that governs commercial terms",
      },
      {
        path: "/data-processing-addendum",
        title: "Data processing addendum",
        description: "Processor obligations, sub-processors, security measures, return or deletion",
      },
      {
        path: RETENTION_PATH,
        title: "Data retention",
        description:
          "Who is responsible for retaining institutional data, what determines retention, how export, deletion and preservation requests are handled, and what is confirmed today versus awaiting confirmation",
      },
      {
        path: "/ai-policy",
        title: "AI policy",
        description: "Commitments on how AEGIS uses institutional data",
      },
      { path: "/pgp", title: "PGP key", description: "Security contact and public key" },
    ],
  },
];

/**
 * Selected buyer guides, not the whole blog: the document stays navigational
 * and the blog index carries the rest. Only published posts are eligible; a
 * slug listed here that is scheduled or missing is skipped, never invented.
 */
const FEATURED_POSTS = [
  "how-to-choose-school-management-system",
  "ai-in-school-erp-governed-intelligence-vs-chatbot",
  "eighteen-thousand-rupee-school-erp-true-cost",
  "school-erp-implementation",
  "school-erp-data-exit",
  "student-data-security-dpdp-checklist",
  "multi-campus-school-governance",
  "trust-board-monthly-reporting",
  "founding-institutional-partner-pilot",
] as const;

export const llmsOptional: LlmsSection = {
  heading: "Optional",
  intro:
    "Selected buyer guides, vendor-neutral where the question is neutral. The blog index lists every published article.",
  links: [
    {
      path: "/blog",
      title: "Blog",
      description: "All published guides and articles, with an RSS feed",
    },
    ...FEATURED_POSTS.flatMap((slug) => {
      const post = blogPosts.find((p) => p.slug === slug);
      return post
        ? [{ path: `/blog/${post.slug}`, title: post.title, description: post.summary }]
        : [];
    }),
  ],
};

/** Lines of the short factual orientation under the summary. */
export function llmsOrientation(): string[] {
  return [
    `- Category: ${product.category}. It includes the record and workflow capabilities expected from institutional ERP software, positioned as a School Operating System; neither "just an ERP" nor "no ERP capabilities".`,
    `- Intended institutions: ${product.audiences.join("; ")}.`,
    `- Geography: ${product.geography}`,
    `- Core distinction: ${product.distinction}`,
    `- Competes on: ${product.competesOn.map((c) => c.toLowerCase()).join(", ")}. It is not designed to be the cheapest attendance, fees and report-card product, and will look expensive to an institution that needs only that.`,
    `- Plans: ${planHierarchy.map((p) => `${p.name} — ${p.summary}`).join(" ")}`,
    `- Pricing availability: ${pricingAvailability.short}`,
    `- Retention: ${retentionPointer.text}`,
    `- Identity: ${identity.baseline.body} ${identity.pro.body} ${identity.enterprise.body} ${identity.notes[0]}`,
    `- ${foundingProgramme.name}: ${foundingProgramme.positionsStatement}`,
    `- Deployment: a bounded deployment can run alongside the institution's current ERP, LMS, payment portal and identity provider, which stay authoritative; consolidation is a later choice and never a precondition of starting.`,
    `- Evidence: ${product.evidenceNote} Product screenshots use synthetic data and are labelled as such.`,
    `- Website source: the code for this site is public at ${siteSource.repoUrl}`,
    `- Operator: ${company.legalNameDisplay} (CIN ${company.cin}, GSTIN ${company.gstin}), ${product.operator.locality}. SquareCampus™ trademark registration pending.`,
  ];
}

function renderSection(section: LlmsSection): string {
  const lines = [`## ${section.heading}`, ""];
  if (section.intro) lines.push(section.intro, "");
  for (const link of section.links) {
    lines.push(`- [${link.title}](${llmsUrl(link.path)}): ${link.description}`);
  }
  return lines.join("\n");
}

/** The complete /llms.txt document. */
export function renderLlmsTxt(): string {
  const parts = [
    "# SquareCampus",
    "",
    `> ${product.shortDescription}`,
    "",
    ...llmsOrientation(),
    "",
    ...llmsSections.map(renderSection).flatMap((s) => [s, ""]),
    renderSection(llmsOptional),
    "",
  ];
  return `${parts
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

/** Every link the document emits, for the sitemap cross-check. */
export function llmsLinks(): LlmsLink[] {
  return [...llmsSections, llmsOptional].flatMap((section) => section.links);
}
